# Generated by Django 3.2.19 on 2023-07-22 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='모임 소개'),
        ),
        migrations.AlterField(
            model_name='community',
            name='is_finished',
            field=models.BooleanField(default=False, verbose_name='종료 여부'),
        ),
    ]
