# Generated by Django 3.2.19 on 2023-07-24 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20230723_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=2000, verbose_name='모임후기')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
            options={
                'db_table': 'tb_reviewmember',
            },
        ),
        migrations.CreateModel(
            name='meetingbookscore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.community')),
            ],
            options={
                'db_table': 'tb_meetingbookscore',
            },
        ),
    ]
