# Generated by Django 3.2.19 on 2023-07-27 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_meetingbookscore_reviewmember'),
    ]

    operations = [
        migrations.DeleteModel(
            name='meetingbookscore',
        ),
    ]
