# Generated by Django 3.2.19 on 2023-07-22 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=2000, verbose_name='리뷰')),
                ('label', models.IntegerField(verbose_name='긍정 부정')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book', verbose_name='도서')),
            ],
            options={
                'db_table': 'tb_review',
            },
        ),
    ]
