# Generated by Django 3.2.19 on 2023-07-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_reviewuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review',
        ),
        migrations.AlterField(
            model_name='review',
            name='label',
            field=models.IntegerField(verbose_name='긍부정라벨'),
        ),
    ]
